# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

pod 'Socket.IO-Client-Swift'

target 'watch-websocket' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for watch-websocket

end

target 'watch-websocket WatchKit App' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for watch-websocket WatchKit App

end

target 'watch-websocket WatchKit Extension' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for watch-websocket WatchKit Extension

end
